LinkAttribute link_attribute
Coordinate[] coordinate
uint64 raw_id
Topology topology
LinkCurvature link_curvature
Guidance[] guidance
NodeIDType start_id
NodeIDType end_id 
FeatureIDType[] feature_point_ids
Node start                                # 兼容   v2 删除
Node end                                  # 兼容   v2 删除
FeaturePoint[] feature_points             # 兼容   v2 删除
LaneById[] lanes                          # 兼容   v2 删除
J6mIntersectionEntryInfo[] j6m_intersection_entry_infos    
LinkIDType[] j6m_lane_ids                     # j6m lanes
LinkIDType[] j6m_link_ids                     # j6m links 