LinkIDType  intersection_id                                           # 路口原始数据Id
LinkIDType[] link_id_s                                                    # 路口linkId列表
LinkIDType[] intersection_successor_id_s                              # 路口后继路口Id列表
LinkIDType[] intersection_predecessor_id_s                            # 路口前驱路口Id列表
bool     is_lane_num_change_areas                                      # 路口是否是车道数变化区域
Coordinate[] intersection_coordinates                                # 路口坐标列表

