std_msgs/Header header
uint8[] localization
uint8[] chassis
uint8[] pad_message
uint8[] pull_over_msg
uint8[] traffic_poles
uint8[] apollo_decision
uint8[] prediction
uint8[] megmap_proto
uint8[] state_context
uint8[] target_trajectory
uint8[] speed_solver_debug_sequence
uint8[] trajectory_solver_debug_sequence
uint8[] planning_log
uint8[] navigator_routing

# 可扩展的二进制流
String2UInt[] scalable_stream

String2Int[] scalable_int
String2Double[] scalable_double
String2Bool[] scalable_bool