deva_common_msgs/Header header

# localization
geometry_msgs/Vector3 translation
geometry_msgs/Quaternion orientation

STBoundary[] st_boundaries
USTBoundary[] ust_boundaries
Crosswalk[] crosswalks
SteeringArrow[] steering_arrows
NoparkingZone[] noparking_zones
Area[] areas
MovingObstacle[] moving_obstacles
StaticObstacle[] general_static_obstacles
TrafficLight[] traffic_light_obstacles
MutableObstacle[] mutable_obstacles
CenterLine[] center_lines
ForkPoint[] fork_points